### ISSUE TITLE
Bug: When a user selects Australia as environment region, the install does not proceed.

### ISSUE THREAD

**Issue by powerplatadmin** [microsoft/industry#255]
### Steps to reproduce

Review + Create Screen has the following error message if you select Australia as the region for environments:

 **error -{
  "code": "InvalidTemplate",
  "message": "Deployment template validation failed: 'The provided value 'australia' for the template parameter 'ppAdminRegion' at line '114' and column '30' is not valid. The parameter value is not part of the allowed value(s): 'europe,unitedstates,asia,japan,india,canada,southamerica,unitedkingdom,france,germany,unitedarabemirates'.'."
}**

### Error Message

```json
**error -{
  "code": "InvalidTemplate",
  "message": "Deployment template validation failed: 'The provided value 'australia' for the template parameter 'ppAdminRegion' at line '114' and column '30' is not valid. The parameter value is not part of the allowed value(s): 'europe,unitedstates,asia,japan,india,canada,southamerica,unitedkingdom,france,germany,unitedarabemirates'.'."
}**
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/microsoft/industry/blob/main/CODE_OF_CONDUCT.md)

**Comment by krnese** [comment]
Thanks for submitting this issue. We will look into it and revert once we have an update/mitigated the issue.
