### ISSUE TITLE
Documentation: Add MC4R Visio diagram in repo

### ISSUE THREAD

**Issue by uday31in** [microsoft/industry#300]
### Documentation Issue

Documentation: Add MC4R Visio diagram in repo.

cc: @victorar 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/microsoft/industry/blob/main/CODE_OF_CONDUCT.md)

**Comment by aydinderya** [comment]
@sasever could you please choose priority & size and put a milestone for this item? Thank you
