### ISSUE TITLE
[AfO Landing Zones] Add required subnets to Network Analytics

### ISSUE THREAD

**Issue by victorar** [microsoft/industry#305]
Please include the two following subnets to the VNet deployed as part of the Network Analytics Landing Zone reference implementation:

PrivateSubnetCIDR
PublicSubnetCIDR

Each subnet must be /26 CIDR.

CC: @rathishrms

**Comment by rathishrms** [comment]
can we please name the subnets the below as thats how its needed for our automation? @victorar @krnese 
adbPublicSubnetCidr, adbPrivateSubnetCidr

**Comment by marvinbuss** [comment]
Quick question: It sounds like we are just proposing customers to leverage Azure Databricks. Is that correct?
Why not Azure Synapse with Kusto/Data Explorer, which is very good for analyzing large amounts of monitoring data (append only)?

**Comment by victorar** [comment]
Closing this issue for the time being due to dependencies being worked out.

**Comment by rathishrms** [comment]
Thanks @victorar, as discussed at this point our automation is creating the required ADB subnets. Will let you know if this approach changes for future. Thanks!
