### ISSUE TITLE
Bug: Observability LZ can take up to 20 mins to deploy

### ISSUE THREAD

**Issue by victorar** [microsoft/industry#307]
### Steps to reproduce

For the Observability Landing Zone reference implementation, select internet-based connectivity, and deploy only the VNet (no Bastion and no monitoring). 

Then, deployment can take ~20 minutes to complete.

### Error Message

```json
No error message. It simply can take a lot of time for the deployment to complete, even when only a VNet resource is deployed.
```

### Screenshots

![image](https://user-images.githubusercontent.com/16934655/181520665-979548e7-1641-472c-b0b0-26e8c45b80e6.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/microsoft/industry/blob/main/CODE_OF_CONDUCT.md)

**Comment by victorar** [comment]
CC: @rathishrms

**Comment by krnese** [comment]
Is the behaviour consistent? If yes, can we get the correlationId to investigate further?

**Comment by victorar** [comment]
Hi @krnese , yes, this behavior has been reported multiple time by different users.

Here's a correlation ID: 0d53a52c-3745-4bb1-af91-5b67c98c0d95

Let me know if more details are needed!

**Comment by krnese** [comment]
After further investigation, this turns out to be circumstantial issue with ARM creating the Microsoft.Resources/deployments resource for nested deployments, hence closing this issue.
