### ISSUE TITLE
Feature: Add support for Norway in the PPLZ reference implementation

### ISSUE THREAD

**Issue by gonadn** [microsoft/industry#328]
### Feature or Idea - What?

We want to use Landing zones, but have a problem, and that is that we it is required in our organization that we create environments with the region "Norway". And we cannot see that this choice is appropriate when defining the various environments under "Landing Zones". Is this something you can add, so that we can create the environment within the region "Norway"?

### Feature or Idea - Why?

Most of the Norwegian organizations want to create there environments in region "Norway". As organisation iam working for cannot use Landing Zones as far we can not select "Norway" as a data region. And this is for the Norwegian Taxoffice. When this option is available it will be easy for all other organisation to use Landing Zone reference.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/microsoft/industry/blob/main/CODE_OF_CONDUCT.md)

**Comment by krnese** [comment]
Thanks for the feedback! We will add this to the backlog and see if we complete the validation on our side in the next couple of days. I will revert as soon as we have an update.
