### ISSUE TITLE
Bug: Power Platform COE Starter Kit not working when Installing it using Power Platform Landing Zone Ref Implementation

### ISSUE THREAD

**Issue by abhishekchowdhuryapmnl** [microsoft/industry#347]
### Steps to reproduce

Hi team we are using Reference Architecture and Landing Zones for Power Platform to setup Power Platform COE inside our organization. Hence we are following all the steps given as part of the documentation provided in the following url as pre-requisite required for the process https://github.com/microsoft/industry/blob/main/foundations/powerPlatform/referenceImplementation/readme.md#pre-requisites also we have full admin rights in both the Azure Environment and Dynamics Environment. 
and then applying the https://aka.ms/ppnorthstar reference Architecture.
Feel free to reach out to me
abhishek.chowdhury@apg-am.nl

### Error Message

```json
We are getting usual exception as provided below
EXCEPTION:
{
• "status": "failed",
• "error": {
• "code": "DeploymentScriptError",
• "message": "The provided script failed with the following error:\r\nMicrosoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 403 (Forbidden).\n at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)\r\nat Invoke-PowerOpsRequest, /root/.local/share/powershell/Modules/PowerOps/0.1.4/PowerOps.psm1: line 64\r\nat Get-PowerOpsTenantSettings, /root/.local/share/powershell/Modules/PowerOps/0.1.4/PowerOps.psm1: line 327\r\nat , /mnt/azscripts/azscriptinput/nsPowerPlatform.ps1: line 215\r\nat , : line 1\r\nat , /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 295. Please refer to https://aka.ms/DeploymentScriptsTroubleshoot for more deployment script information."
• }
•}
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/microsoft/industry/blob/main/CODE_OF_CONDUCT.md)

**Comment by daltondhcp** [comment]
Sorry for the slow response. 

The error message indicates that the "Admin Application Registration" has not been done successfully. Can you retry that step please? 
![image](https://user-images.githubusercontent.com/16622613/199012301-ad7c5de5-caa0-4cb1-b65d-827844e2ab9e.png)

**Comment by abhishekchowdhuryapmnl** [comment]
HI @daltondhcp thanks for the reply we again retried with all the recommended steps but still no luck. Please see the attached document for the exception and steps followed. Is it possible to do a joined session to find out problem.
[PPCOE-Steps.pdf](https://github.com/microsoft/industry/files/9908741/PPCOE-Steps.pdf)

**Comment by daltondhcp** [comment]
Based on the error message, it looks like your tenant have no Power Platform licenses. Can you confirm that you have PP licenses?

**Comment by abhishekchowdhuryapmnl** [comment]
Hi @daltondhcp  thanks for the reply as per knowledge my infra team has provisioned PP licenses for the environment, but I will check and get back to you.

**Comment by daltondhcp** [comment]
@abhishekchowdhuryapmnl - did you figure out if you had licenses?

**Comment by abhishekchowdhuryapmnl** [comment]
Hi @daltondhcp yes you were correct the licenses were not on the specified environment. So I asked the infra to provision licenses for the specified environment and then I will get back to you, if any further progress is made for now I can close this issue and wait for licenses. Thanks for your support.
