### ISSUE TITLE
Documentation: Unable to locate PowerOps module

### ISSUE THREAD

**Issue by RakeshPower** [microsoft/industry#356]
### Documentation Issue

Hi Team,

Unable to locate "**PowerOps module**", however able to register app with following:
$appId = "CLIENT_ID_FROM_AZURE_APP"

# Login interactively with a tenant administrator for Power Platform
Add-PowerAppsAccount -Endpoint prod -TenantID $tenantId 

# Register a new application, this gives the SPN / client application same permissions as a tenant admin
New-PowerAppManagementApp -ApplicationId $appId

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/microsoft/industry/blob/main/CODE_OF_CONDUCT.md)

**Comment by daltondhcp** [comment]
Thank you for raising this.

Can you share the error message as well as confirm that you used the -AllowPreRelease flag when trying to install the module. 
<img width="581" alt="image" src="https://user-images.githubusercontent.com/16622613/211313687-6c483a2d-0bd2-4005-844d-66d04457aaee.png">

Nevertheless, we will update the documentation to use the 
Microsoft.PowerApps.Administration.PowerShell module instead to make it simpler.
