### ISSUE TITLE
Bug: Reference implementation assign two polices to Citizen Developer Enviornment

### ISSUE THREAD

**Issue by RakeshPower** [microsoft/industry#357]
### Steps to reproduce

Hi Team,

while implementing landing zone it ia assigning two DLP policies to citizen developer environments(tenant level as well as CitizenDev one? Is it as per design or a bug ? As combination of two policies (citizendev + tenant level) doesn’t serve end result.
 Such as cannot use Sharepoint and HTTP together. Seems like reference implementation shall only assign single policy citizendev to citizen environment not tenant level. Please advise

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/microsoft/industry/blob/main/CODE_OF_CONDUCT.md)

**Comment by krnese** [comment]
Hi Rakesh, we are still reviewing this internally, but summarise the desired state from you:
All environments (i.e., landing zones that are being created) should be excluded from the tenant level DLP?

**Comment by RakeshPower** [comment]
Thanks a lot!
Was expecting the same that landing zones should be excluded from Tenant Level DLP. Thanks.
