### ISSUE TITLE
add KV Min Size and LifeTime trigger Policies

### ISSUE THREAD

**Issue by sasever** [microsoft/industry#416]
Enhance the FSI Secure by Default Key Vault Policy initiative 
by adding 4 built-in policies:

1. Keys using RSA cryptography should have a specified minimum key size
2. [Preview]: Azure Key Vault Managed HSM keys using RSA cryptography should have a specified minimum key size
3. Certificates using RSA cryptography should have the specified minimum key size
4. Certificates should have the specified lifetime action triggers

**Comment by krnese** [comment]
Closing this as the PR (#417 ) was merged earlier. Great work!
