### ISSUE TITLE
Add option to provide custom BGP communities

### ISSUE THREAD

**Issue by victorar** [microsoft/industry#447]
Add option to provide custom BGP community values for VNets deployed (hub and spoke VNets) when ExpressRoute connectivity is configured. This would allow customers to receive both, custom and regional BGP community values for the VNets in Azure (advertisement done via ExpressRoute Private Peering).

More details here: https://learn.microsoft.com/en-us/azure/expressroute/how-to-configure-custom-bgp-communities

Please note that this capability in currently in public preview, and should be highlighted accordingly in the accelerator UX.

**Comment by krnese** [comment]
Closing this issue as the work is completed
