### ISSUE TITLE
Bug: AFO Landing Zone Deployment Issue

### ISSUE THREAD

**Issue by Joshi4391** [microsoft/industry#488]
### Steps to reproduce

Deployed AFO LZ with Single subscription.

### Error Message

```json
After successful deployment of LZ, in next step, I am getting below Error.

{  "shellProps": {    "sessionId": "eddfdeed350b4128a50147449704f332",    "extName": "HubsExtension",    "contentName": "ResourceMenuBlade"  },  "error": {    "message": "Resource not found",    "code": 404,    "details": {      "htmlTemplate": "The resource was not found, it may have been deleted. If this was launched from a pinned tile on the dashboard, it should be removed.<br /><br />Resource ID: _REDACTED_<br /><br />Status Code: 404<br /><br />Status Message: The resource ID provided is not a valid ID (not a subscription, resource group or resource ID)."    }  }}
```

### Screenshots

<img width="593" alt="image" src="https://github.com/microsoft/industry/assets/112846514/36c448b1-9653-468e-8cf3-ac71b18bb3e2">

<img width="522" alt="image" src="https://github.com/microsoft/industry/assets/112846514/3935bce3-1e9a-484c-b7c0-ac54fac48aa9">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/microsoft/industry/blob/main/CODE_OF_CONDUCT.md)

**Comment by victorar** [comment]
Hi @Joshi4391 , thanks for reporting this. Can you help me describing the steps to reproduce the issue? Was it when you clicked in the "Go to management group" button from your second screenshot?

**Comment by Joshi4391** [comment]
Yes @victorar. After getting successful deployment, The AFO deployment page is redirecting me to "Go to management group" as a next step, where I am getting Resource Not found error.

Note: I'm deploying AFO landing zone with single subscription.

**Comment by victorar** [comment]
Hi @Joshi4391 thanks for the additional details. We have identified the issue, and will shortly revert back with the fix.

**Comment by Joshi4391** [comment]
Great @victorar ! Could you pls let us know that where is the problem and what is creating this issue ? also let us know that Is it from our side or MSFT side ?

**Comment by Joshi4391** [comment]
HI @victorar any update on fix ?

**Comment by Joshi4391** [comment]
Hi @victorar / @krnese , Could you pls let us know by when we'll get this fix ?

**Comment by krnese** [comment]
Hi @Joshi4391 , we are working on a fix for this now in addition to a larger update for AFO deployment, so we will revert here as soon as we have it ready.

**Comment by Joshi4391** [comment]
Thanks @krnese

**Comment by Joshi4391** [comment]
@krnese Is this merged with current AFO LZ deployment UI ? If yes then I can start deploying LZ.

**Comment by krnese** [comment]
It has not merged yet, will let you know as soon as it is completed

**Comment by Joshi4391** [comment]
@krnese Is is merged now ??

**Comment by krnese** [comment]
It will be merged this week.

**Comment by Joshi4391** [comment]
okay. Thanks a lot

**Comment by krnese** [comment]
Can you please try again, from https://aka.ms/afoRi ?
We will be updating the documentation, screenshots etc. in the coming days.

Thank you
